name: .NET Core Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x  # Replace with the actual version

    - name: Restore and Build
      run: dotnet build A4L_Deployement.sln --configuration Release
      working-directory: A4L_Deployement

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-app-artifact
        path: A4L_Deployement/bin/Release/net6.0/publish/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: dotnet-app-artifact
        path: dotnet-app-artifact

    - name: Deploy to Server
      run: |
        # Here, you can add commands to deploy the .NET application to your server.
        # This might involve copying files, setting up a web server, etc.
        # Replace the following line with your deployment commands.

        # Example:
        # sudo cp -r dotnet-app-artifact/* /var/www/mydotnetapp/
        
        echo "Deployment completed"
